required = [
  "github.com/alvaroloes/enumer"
]

[[constraint]]
  name = "gopkg.in/d4l3k/messagediff.v1"
  version = "1.2.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.6"

[prune]
  go-tests = true
  unused-packages = true
